version: '3.9'

services:
  radio:
    env_file:
      - ./.env
    build:
      context: ./
    ports:
      - 5000:5000
  
  tracker:
    image: registry.gitlab.com/maissacrement/tracker:latest
    ports:
      - "7070:7070"
    environment:
      - PORT=7070