#!/bin/bash

function runTest() {
    curl http://0.0.0.0:5000/magnet \
        -X POST -H 'content-type: application/json' \
        -H 'Accept: application/json' \
    --data @./json/Ble.json
}

function runMouseDataTest() {
    curl http://0.0.0.0:5000/dynmagnet \
        -X POST -H 'content-type: application/json' \
        -H 'Accept: application/json' \
    --data @./json/bluetooth.json
}

function main() {
    #runTest
    runMouseDataTest
}

main
